apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aiops-quality.fullname" . }}
  labels:
    {{- include "aiops-quality.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "aiops-quality.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "aiops-quality.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        prometheus.io/scrape: {{ .Values.metrics.enabled | quote }}
        prometheus.io/path: {{ .Values.metrics.path | quote }}
        prometheus.io/port: {{ .Values.metrics.port | quote }}
    spec:
      containers:
        - name: api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          env:
            - name: MODEL_PATH
              value: {{ .Values.env.modelPath | quote }}
            - name: DRIFT_Z_THRESHOLD
              value: {{ .Values.env.driftZThreshold | quote }}
            - name: DRIFT_WEBHOOK_URL
              value: {{ .Values.env.driftWebhookUrl | quote }}
            - name: LOG_LEVEL
              value: {{ .Values.env.logLevel | quote }}
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
