apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aiops-quality-api
  namespace: infra-tools
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/vdubyna/go-it-ai-ml.git
    targetRevision: main
    path: aiops-quality-project/helm
    helm:
      releaseName: aiops-quality-api
  destination:
    server: https://kubernetes.default.svc
    namespace: application
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  revisionHistoryLimit: 3
