apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: infra-tools
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: minio
    targetRevision: 13.7.2
    helm:
      releaseName: minio
      valuesObject:
        global:
          security:
            allowInsecureImages: true
        image:
          repository: bitnamilegacy/minio
        clientImage:
          repository: bitnamilegacy/minio-client
        auth:
          rootUser: minio
          rootPassword: minio123
        defaultBuckets: "mlflow-artifacts"
        service:
          type: ClusterIP
          ports:
            api: 9000
        console:
          enabled: true
          service:
            type: ClusterIP
        persistence:
          enabled: false
        resourcesPreset: "none"
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: application
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
  revisionHistoryLimit: 2
