apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlflow-postgres
  namespace: infra-tools
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: postgresql
    targetRevision: 12.5.6
    helm:
      releaseName: mlflow-postgres
      valuesObject:
        global:
          security:
            allowInsecureImages: true
        image:
          repository: bitnamilegacy/postgresql
        auth:
          username: mlflow
          password: mlflowpass
          database: mlflow
        architecture: standalone
        primary:
          persistence:
            enabled: false
          resourcesPreset: "none"
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: application
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
  revisionHistoryLimit: 2
