apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pushgateway
  namespace: infra-tools
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: prometheus-pushgateway
    targetRevision: 3.6.0
    helm:
      releaseName: pushgateway
      valuesObject:
        fullnameOverride: pushgateway
        service:
          type: ClusterIP
          port: 9091
          targetPort: 9091
        serviceAnnotations:
          prometheus.io/scrape: "true"
          prometheus.io/port: "9091"
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 250m
            memory: 256Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
  revisionHistoryLimit: 2
